#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 20 00:19:45 2020

@author: nishi
"""

def count_words(strng): 
    strng_list = strng.split() 
    return len(strng_list) 
 
print(count_words("Hey my name is Nishi!"))